DEFAULT_MESSAGE_RESPONSE_GENERIC_ERROR ="Unknown error"
DEFAULT_MESSAGE_RESPONSE_APP_ERROR ="Error: {}"
DEFAULT_MESSAGE_RESPONSE_NULL_REQUEST ="Request is null"
DEFAULT_MESSAGE_RESPONSE_NO_FIELDS ="Request has no fields"
DEFAULT_MESSAGE_RESPONSE_SOME_REQUIRED_FIELDS_EMPTY ="Some required fields are empty"

DEFAULT_EXCEPTION_DIRECTORY_NOT_FOUND ="Directory not found"