# TODO add i18n support
DEFAULT_MESSAGE_RESPONSE_GENERIC_ERROR ="Unknown error"
DEFAULT_MESSAGE_RESPONSE_APP_ERROR ="Error: {}"
DEFAULT_MESSAGE_RESPONSE_NULL_REQUEST ="Request is null"
DEFAULT_MESSAGE_RESPONSE_NO_FIELDS ="Request has no fields"
DEFAULT_MESSAGE_RESPONSE_SOME_REQUIRED_FIELDS_EMPTY ="Some required fields are empty"

DEFAULT_EXCEPTION_DIRECTORY_NOT_FOUND ="Directory not found"
DEFAULT_EXCEPTION_NO_FILE_MOVED ="No files were moved"
DEFAULT_EXCEPTION_ERROR_READING_WORDS_FILE = "Error when reading files"
DEFAULT_EXCEPTION_ERROR_PERSISTING_WORDS ="Could not persist words"